In [1]:
print("hello")


hello


In [2]:
print("hello world")

hello world


In [3]:
a=10
b=20
print(a+b)

30


In [3]:
import numpy as np

In [9]:
arr1=np.array([1,2,3,4,5])
arr1[2:4]=[20,30]
arr1

array([ 1,  2, 20, 30,  5])

In [23]:
arr3= np.array ([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
arr3[1:3,1:3]=1
arr3




array([[1, 2, 3, 4],
       [5, 1, 1, 8],
       [9, 1, 1, 2]])

In [27]:
arr4=np.array([[1,2,3],[4,5,6],[5,6,7],[6,7,8],[8,9,6],[6,7,3],[1,6,3]])
arr4[:,::2]

array([[1, 3],
       [4, 6],
       [5, 7],
       [6, 8],
       [8, 6],
       [6, 3],
       [1, 3]])

In [46]:
arr4=np.array([[1,2,3],[4,5,6],[5,6,7],[6,7,8],[8,9,6],[6,7,3],[1,6,3]])
arr4[[0,1,4]]=255
arr4%2==0

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [ True, False,  True],
       [False, False, False],
       [ True, False, False],
       [False,  True, False]])

In [5]:
arr5= np.array([[12, 34, 56],  
                [78, 90, 23],  
                [45, 67, 89]])
arr5

array([[12, 34, 56],
       [78, 90, 23],
       [45, 67, 89]])

In [22]:
arr6=arr5[[2,1,0],:]
np.argmin(arr6)
arr6

array([[45, 67, 89],
       [78, 90, 23],
       [12, 34, 56]])

In [36]:
a=np.full((10,5),2)
a.shape
np.reshape(a,(5,10))

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [6]:
import numpy as np

In [10]:
arrya1=np.random.randint(1,100),(2,3,4)
arrya1

(52, (2, 3, 4))