In [1]:
print("hello")


hello


In [2]:
print("hello world")

hello world


In [3]:
a=10
b=20
print(a+b)

30


In [3]:
import numpy as np

In [9]:
arr1=np.array([1,2,3,4,5])
arr1[2:4]=[20,30]
arr1

array([ 1,  2, 20, 30,  5])

In [23]:
arr3= np.array ([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
arr3[1:3,1:3]=1
arr3




array([[1, 2, 3, 4],
       [5, 1, 1, 8],
       [9, 1, 1, 2]])

In [27]:
arr4=np.array([[1,2,3],[4,5,6],[5,6,7],[6,7,8],[8,9,6],[6,7,3],[1,6,3]])
arr4[:,::2]

array([[1, 3],
       [4, 6],
       [5, 7],
       [6, 8],
       [8, 6],
       [6, 3],
       [1, 3]])

In [46]:
arr4=np.array([[1,2,3],[4,5,6],[5,6,7],[6,7,8],[8,9,6],[6,7,3],[1,6,3]])
arr4[[0,1,4]]=255
arr4%2==0

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [ True, False,  True],
       [False, False, False],
       [ True, False, False],
       [False,  True, False]])

In [5]:
arr5= np.array([[12, 34, 56],  
                [78, 90, 23],  
                [45, 67, 89]])
arr5

array([[12, 34, 56],
       [78, 90, 23],
       [45, 67, 89]])

In [22]:
arr6=arr5[[2,1,0],:]
np.argmin(arr6)
arr6

array([[45, 67, 89],
       [78, 90, 23],
       [12, 34, 56]])

In [36]:
a=np.full((10,5),2)
a.shape
np.reshape(a,(5,10))

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [11]:
import numpy as np

In [22]:
arr3=np.reshape(np.arange(1,26),(5,5))
arr3
arr4=arr3[[4,2,0,3,1]]
arr4
arr5=arr4[:,[1,3,0,4,2]]
arr5

array([[22, 24, 21, 25, 23],
       [12, 14, 11, 15, 13],
       [ 2,  4,  1,  5,  3],
       [17, 19, 16, 20, 18],
       [ 7,  9,  6, 10,  8]])

In [28]:
arr6=np.arange(1,37)
arr6=np.reshape(np.arange(1,37),(6,6))
arr6
arr6[[2,4,5],[3,5,0]]

array([16, 30, 31])

In [51]:
arr7=np.random.randint(0,101,(10,4))
arr7
np.max(arr7,axis=1)

array([100,  42,  96,  99,  66,  68,  77,  99,  29,  82])

In [58]:
arr8=np.arange(1,17)
arr8=np.reshape(np.arange(1,17),(4,4))
arr8
arr9=np.transpose(arr8)
arr9

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [59]:
matrix_a=np.random.randint(1,10,(3,3))
matrix_b=np.random.randint(1,10,(3,10))
np.matmul(matrix_a,matrix_b)

array([[ 39,  68,  91,  53,  42,  61,  78,  79,  76,  37],
       [ 51,  94, 119,  80,  54,  84,  89,  89,  93,  44],
       [ 54,  96, 126, 119, 102, 113,  91,  60,  71,  57]])

In [60]:
a=np.array((2,5,13))
b=np.array((10,2,1))
np.linalg.norm(a-b)

14.730919862656235